config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resource :stylesheets do
      post :restore
    end
  end

  match 'dandystyles', to: 'stylesheets#show', via: :all
end

app/models/spree/blank_stylesheet.rb
module Spree
  class BlankStylesheet
    def style_compressed
      ''
    end
  end
end

app/models/spree/store_decorator.rb
Spree::Store.class_eval do
  has_attached_file :logo,
                    url: "/spree/stores/:id/:style/:basename.:extension",
                    styles: { original: "250x250>" },
                    path: ":rails_root/public/spree/stores/logo/:basename.:extension"

  validates_attachment :logo,
                       content_type: { content_type: %r(image/.*) },
                       size: { in: 0..2.megabytes }

  attr_accessor :logo_content_type, :logo_file_size
end

app/models/spree/stylesheet.rb
module Spree
  class Stylesheet < ActiveRecord::Base
    validates :style_raw, presence: true
    validate :compilation

    has_paper_trail only: [:style_raw],
                    class_name: 'Spree::StylesheetVersion'

    def self.load_style
      first || BlankStylesheet.new
    end

    private

    def compilation
      self.style_compressed = rendered_sass
    end

    def sass_engine
      Sass::Engine.new style_raw, syntax: :scss, style: :compressed
    end

    def rendered_sass
      sass_engine.render
    rescue => err
      errors.add :style_raw, err.message
      nil
    end
  end
end

app/models/spree/stylesheet_version.rb
module Spree
  class StylesheetVersion < PaperTrail::Version
    belongs_to :user,
               foreign_key: 'whodunnit'
  end
end

app/models/spree/unknown_user.rb
module Spree
  class UnknownUser
    def id
      Spree.t('dandify.admin.unknown')
    end

    def email
      Spree.t('dandify.admin.unknown')
    end
  end
end

app/models/spree/user_decorator.rb
Spree::User.class_eval do
  has_many :editions,
           foreign_key: 'whodunnit',
           class_name:  'Spree::StylesheetVersion'
end

app/models/spree/user_identifier.rb
module Spree
  class UserIdentifier
    delegate :id, to: :user

    def initialize(user)
      @user = user || UnknownUser.new
    end

    private

    attr_reader :user
  end
end

app/controllers/spree/admin/general_settings_controller_decorator.rb
Spree::Admin::GeneralSettingsController.class_eval do
  def update
    params.each do |name, value|
      next unless Spree::Config.has_preference? name

      Spree::Config[name] = value
    end

    if current_store.update_attributes(store_params)
      flash[:success] = Spree.t(:successfully_updated,
                                resource: Spree.t(:general_settings))
    else
      flash[:error] = current_store.errors.full_messages.join(". ")
    end

    redirect_to edit_admin_general_settings_path
  end
end

app/controllers/spree/admin/stylesheets_controller.rb
module Spree
  module Admin
    class StylesheetsController < BaseController
      helper Spree::Admin::StylesheetHelper

      respond_to :html

      before_action :set_style, except: [:restore]

      def create
        update_action :new
      end

      def update
        update_action :edit
      end

      def destroy
        @style.destroy

        redirect_to admin_stylesheets_path, flash: {
          success: Spree.t('dandify.admin.flash.destroyed')
        }
      end

      def restore
        response = rollback_version

        redirect_to admin_stylesheets_path, flash: {
          response => Spree.t("dandify.admin.flash.#{response}.restore")
        }
      end

      def user_for_paper_trail
        Spree::UserIdentifier.new(current_spree_user).id
      end

      private

      def rollback_version
        @style = PaperTrail::Version.find(params[:id]).reify
        @style.save!
        :success
      rescue
        :error
      end

      def update_action(type)
        if @style.update(style_params)
          redirect_to admin_stylesheets_path, flash: {
            success: Spree.t("dandify.admin.flash.success.#{type}")
          }
        else
          render type
        end
      end

      def set_style
        @style = Spree::Stylesheet.first_or_initialize
      end

      def style_params
        params.require(:stylesheet).permit(:style_raw)
      end
    end
  end
end

app/controllers/spree/stylesheets_controller.rb
module Spree
  class StylesheetsController < Spree::StoreController
    before_filter :set_response_format

    def show
      @style = Spree::Stylesheet.load_style
    end

    private

    def set_response_format
      request.format = :css
    end
  end
end

app/helpers/spree/admin/navigation_helper_decorator.rb
Spree::Admin::NavigationHelper.class_eval do
  def link_to_restore_url(url, options = {})
    name = options[:name] || Spree.t('dandify.admin.icons.restore')
    options[:class] = 'restore-resource btn btn-sm btn-primary icon icon-clone'
    options[:data] = { confirm: Spree.t('dandify.admin.confirm.restore'),
                        action: 'restore' }
    link_to_with_icon('history', name, url, options)
  end

  def link_to_destroy_url
    options = {
      class: 'btn btn-danger',
      data: {
        confirm: Spree.t('dandify.admin.confirm.destroy'),
        action: 'delete'
      },
      method: :delete
    }

    link_to_with_icon 'delete',
                      Spree.t('dandify.admin.icons.destroy'),
                      admin_stylesheets_path,
                      options
  end
end

app/helpers/spree/admin/stylesheet_helper.rb
module Spree
  module Admin
    module StylesheetHelper
      def dandify_version_email(user_id)
        user = if user_id.nil? || user_id == Spree.t('dandify.admin.unknown')
          UnknownUser.new
        else
          User.find(user_id)
        end

        user.email
      end

      def previous_versions
        PaperTrail::Version.all
      end
    end
  end
end

app/helpers/spree/base_helper_decorator.rb
Spree::BaseHelper.class_eval do
  def logo(image_path = Spree::Config.logo)
    image_path = current_store.logo.url if current_store.logo.exists?

    link_to image_tag(image_path, alt: current_store.name), spree.root_path
  end
end

app/views/spree/admin/stylesheets/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/ace.js' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.0/mode-css.js' %>
<% end %>

<div data-hook="admin_style_form_fields" class="col-md-12">
  <div class="form-group 12-row">
    <div data-hook="admin_stylesheet_form_style_raw" class="form-group field spree-ace-field">
      <div id="editor"></div>
      <%= f.field_container :style_raw, class: ['form-group'] do %>
        <%= f.label :style_raw, Spree.t('dandify.admin.labels.style_raw') %>
        <%= f.text_area :style_raw, rows: '13', class: 'form-control' %>
        <br/><span class="help-block"><%= Spree.t('dandify.admin.notes.sass') %></span>
      <% end %>
    </div>
  </div>
</div>

<script>
  (function() {
    var cssEditor, stylesheetText = $("#stylesheet_style_raw");

    $(function() {
      cssEditor = ace.edit("editor");
      cssEditor.getSession().setMode("ace/mode/css");
      cssEditor.setValue(stylesheetText.text());
    });

    $('#new_stylesheet, .edit_stylesheet').submit(function(event) {
      stylesheetText.text(cssEditor.getValue());
    });
  })();
</script>

app/views/spree/admin/stylesheets/_versions.html.erb
<h4>
  <%= Spree.t('dandify.admin.headers.revisions') %>
</h4>
<table class="table" id="listing_versions" data-hook="listing_style_versions">
  <thead>
    <tr data-hook="stylesheets_show_index_headers">
      <th><%= Spree.t('dandify.admin.headers.on') %></th>
      <th><%= Spree.t('dandify.admin.headers.author') %></th>
      <th><%= Spree.t('dandify.admin.headers.action') %></th>
      <th data-hook="admin_stylesheets_show_header_actions" class="actions"></th>
    </tr>
  </thead>
  <tbody>
  <% versions.reverse.each_with_index do |version| %>
    <tr data-hook="admin_stylesheets_show_rows" class="<%= cycle('odd', 'even') %>">
      <td class="align-center">
        <%= version.created_at.to_date %>
      </td>
      <td><%= link_to(dandify_version_email(version.whodunnit), admin_user_path(version.whodunnit.to_i)) %></td>
      <td>
        <%= Spree.t("dandify.admin.action.#{version.event}") %>
      </td>
      <td class='actions align-center' data-hook="admin_stylesheets_show_row_actions">
        <%= link_to_restore_url restore_admin_stylesheets_path(id: version.id), title: 'admin_restore_stylesheet', no_text: true, method: :post %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/stylesheets/edit.html.erb
<%= render 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t('dandify.admin.title.edit') %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: {target: @style} %>

<%= form_for @style, url: admin_stylesheets_path do |f| %>
  <fieldset data-hook="edit_style">
    <%= render partial: 'form', locals: {f: f} %>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'ok', 'submit', { class: 'btn-success' } %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_stylesheets_path, icon: 'remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/stylesheets/new.html.erb
<%= render 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t('dandify.admin.title.new') %>
<% end %>

<%= render partial: 'spree/shared/error_messages', locals: {target: @style} %>

<%= form_for @style, url: admin_stylesheets_path do |f| %>
  <fieldset data-hook="new_style">
    <%= render partial: 'form', locals: {f: f} %>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'ok', 'submit', { class: 'btn-success' } %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), admin_stylesheets_path, icon: 'remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/stylesheets/show.html.erb
<%= render 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_title do %>
  <%= Spree.t('dandify.admin.title.show') %>
<% end %>

<% content_for :page_actions do %>
  <% if @style.persisted? %>
    <%= link_to_with_icon 'edit', Spree.t('dandify.admin.buttons.edit'), edit_admin_stylesheets_path, class: 'btn btn-success' %>
    <%= link_to_destroy_url %>
  <% else %>
    <%= link_to_with_icon 'plus', Spree.t('dandify.admin.buttons.new'), new_admin_stylesheets_path, class: 'btn btn-success' %>
  <% end %>
<% end %>

<% content_for :head do %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/prism/0.0.1/prism.min.css' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/prism/0.0.1/prism.min.js' %>
<% end %>

<p class="notice"><%= notice %></p>

<% if @style.persisted? %>
  <pre><code class="language-css"><%= @style.style_raw %></code></pre>

<% else %>
  <div class="no-objects-found">
    <%= Spree.t('dandify.admin.no_resource_found') %>,
    <%= link_to Spree.t('dandify.admin.create_one'), new_admin_stylesheets_path %>!
  </div>
<% end %>

<div class="row">
  <% if PaperTrail::Version.count > 1 %>
    <%= render partial: 'versions', locals: { versions: previous_versions } %>
  <% end %>
</div>

app/views/spree/stylesheets/show.css.erb
<%= raw @style.style_compressed %>